apiVersion: api.practice.com/v1alpha1
kind: Task
metadata:
  name: mytask-test-entrypoint
spec:
  steps:
    - name: step1
      image: busybox:1.28
      command: [ "sh","-c" ]
      args: [ "echo step1" ]
    - name: step2
      image: shenyisyn/task:v1
      args:
        - echo
        - "step test2"