apiVersion: api.practice.com/v1alpha1
kind: Task
metadata:
  name: example-taskflow
spec:
  steps:
    - name: step1
      image: busybox:1.28
      command: [ "sh","-c" ]
      args: [ "echo step1" ]
    - name: step2
      image: busybox:1.28
      command: [ "sh","-c" ]
      args: [ "echo step2" ]
    - name: step3
      image: devopscube/kubernetes-job-demo:latest
      args: [ "100" ]